@Restuarants.Api_HostAddress = https://localhost:7275

 

###

GET {{Restuarants.Api_HostAddress}}/api/restuarants

###

GET https://localhost:7275/api/Restuarants/87076add-f9eb-4774-7a97-08dcbbb4d9ae

###
